### ISSUE TITLE
ブランチルールを下記に作成してreadmeから参照する。

### ISSUE THREAD

**Issue by yus-sasaki** [denso-create/LightningReview-RevxFile#7]
docs/branch-rule.md

以下に案を記す。

## ブランチ
git-flowの考え方を踏襲。
* `main`ブランチはFIXした公開版ソースとする。
* 開発用ブランチ `develop` を用意し、ここからフィーチャーブランチを分岐する。
* `develop`ブランチで公開用バージョンが完成したら`main`ブランチにマージする。
webページでのreadme編集や閲覧対象が`main`ブランチのファイルになるよう、デフォルトブランチは`main`のままにしておく。

## 自動ビルド・テスト
* mainブランチの変更をトリガとし、github actions のスクリプトで自動ビルド・テストを行う   
    - main以外のブランチでは実行しない
    - ソース以外の変更で実行されないよう srcフォルダ以下の変更のみを対象とする

```yml
on:
  push:
    branches: [ main ]
    paths: [ 'src' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src' ]
```

## パッケージ公開
* `main`ブランチを対象にnugetパッケージを作成、公開する。
* パッケージ作成から公開までgithub actionsのスクリプトで実行する。
